version: '3.8'
networks:
  asteroids:
    ipam:
      config:
        - subnet: 172.10.0.0/24

services:
  asteroidapi:
    build:
      context: ./
      dockerfile: src/AtmiraAPI/Dockerfile
      # args:
      #   URLORIGIN: "https://www.marca.com/" 
    networks:
      asteroids:
        aliases:
          - asteroidapi
        ipv4_address: 172.10.0.8
    hostname: asteroidapi
    ports:
      - "81:80"